### ISSUE TITLE
Multiple homedirs check

### ISSUE THREAD

**Issue by cPAusaf** [cPanelPeter/acctinfo#4]
8329511

Example: Account 'test' gets setup on /home2, wwwacct gets updated to use /home3 for HOMEDIR. Running cruft on account 'test' seems to show /home3/test/ as missing (but /home2/test/ exists)

**Comment by cPanelPeter** [comment]
Added a loop to check HOMEMATCH{1..9}/username if HOMEDIR/username doesn't exist. 
That should cover this.  Fixed in v2.4.69.

Thanks.
