### ISSUE TITLE
Request: Verify domain exists in httpd.conf

### ISSUE THREAD

**Issue by cPAusaf** [cPanelPeter/acctinfo#5]
Not for cruft but just the default:
# acctinfo domain.tld

This will help with identifying the 'The system cannot determine the base domain for “domain.tld”' issues

**Comment by cPanelPeter** [comment]
So you want a check to see if the domain.tld exists in httpd.conf on the main output? 
Because cruft check already does that.  I'm not sure what the exact purpose of that is, and don't want to output duplicate data if I don't need to.
