### ISSUE TITLE
Code block tags

### ISSUE THREAD

**Issue by trobotham** [cPanelPeter/acctinfo#6]
In bda5535871c9391995408df65bd13a2de2f10522 it appears that you added code tags the output, I use this as an alias and this poses a problem for me as I have a hotkey which pastes in codeblocks already.

Is there any way that you can add either a ENV var or a cli flag to disable it (doesn't really matter if it is enabled by default) as just a way to disable it.

Thanks!

**Comment by jlsonline** [comment]
Agree with trobotham.  Breaks my aliases too.  Seems like an argument/flag would be best.

**Comment by cPanelPeter** [comment]
Fixed.  Added a --nocode option

**Comment by cPanelPeter** [comment]
Added --nocode option to skip code blocks.
