### ISSUE TITLE
Have --scan ignore images

### ISSUE THREAD

**Issue by cPAusaf** [cPanelPeter/acctinfo#7]
It currently reports images as being a suspicious file (only really see with .png and .svg extensions)

**Comment by cPanelPeter** [comment]
Thanks. 

Hackers can hide files/programs/anything in any file (including images). 
Then they could run a script later to extract and/or compile what they have hidden... 

For example, one could embed a malicious executable (or smaller script) within multiple images on a website. When a user goes to the website, they download the images.

I have seen this mostly with jpg and gif images.  And I admit I don't think it's common in png or SVG images so, in the next version, I will exclude those, but I won't (at this time) exclude jpg or gif.
